### ISSUE TITLE
No such container

### ISSUE THREAD

**Issue by adamvm** [PacktPublishing/Learn-MongoDB-4.0#3]
Date of repo clone / book open via safari / execution of commands: 20 Sept 2020

Book
![image](https://user-images.githubusercontent.com/5563693/93695073-0d0b0d80-fb13-11ea-9c1c-5a924dc94a86.png)

Terminal:

![image](https://user-images.githubusercontent.com/5563693/93695081-2c099f80-fb13-11ea-8b11-501478d586ae.png)

**Comment by adamvm** [comment]
![image](https://user-images.githubusercontent.com/5563693/93695090-4cd1f500-fb13-11ea-8136-9215eb567254.png)

**Comment by dbierer** [comment]
Adam --
The container you built was "learn-mongo-server-1". The container you tried to exec is "learn-mongo-installation-1". You can only exec the container that's built and up.

If you wish to build "learn-mongo-installation-1" you must first change to "/path/to/repo/chapters/02". From there run `docker-compose build`. Then bring it up:  `docker-compose up -d`.  When done using it, don't forget to bring it down:  `docker-compose down`
