### ISSUE TITLE
docker-compose build fails when trying to run init.sh (step 6 in Dockerfile)

### ISSUE THREAD

**Issue by kohlmannmark** [PacktPublishing/Learn-MongoDB-4.0#4]
Error message: /tmp/init.sh not found
Environment: docker for windows with wsl2 backend
**Solution**: change RUN to CMD in Dockerfile line 12.

Maybe others have this issue as well.

**Comment by jams008** [comment]
i fixed your error. #5

**Comment by kohlmannmark** [comment]
Thanks, appreciate it.
