### ISSUE TITLE
Can't ping learning.mongodb.local

### ISSUE THREAD

**Issue by penguin22** [PacktPublishing/Learn-MongoDB-4.0#7]
Docker Desktop is the latest.
Mac big sur(latest) or Windows 10 (updated).
Following strictly to book tutorials.
I can't ping  locally outside of container, urls locally doesn't work.
I tried to look up answers, such as stackoverflow, anywhere available. Unfortunately, none works.
I can't cross the router bridge.
I have to raise the issue.

**Comment by penguin22** [comment]
I find time to set the environment in Ubuntu 18...LTS, No problem happens, with ping outside successfully.
As I said, I tried in Windows 10 pro, I don't think  I have missed any. I don't want to waste more time. 
Earlier versions could work for both macos and windows without latest version of Docker.
Anyway, I can go ahead with the book with Linux, it's good enough.

**Comment by dbierer** [comment]
Sorry for the late response.  I will run a test on a Windows 10 computer and see if I can duplicate the problem.

**Comment by penguin22** [comment]
Thanks!
Inside Ubuntu, , or Even MAC Big Sur VMware inside Ubutun, Both work well.
Hope to have any useful info to you.
I can be reading the book now.



On Apr 1, 2021, at 13:26, Doug Bierer ***@***.******@***.***>> wrote:



Sorry for the late response. I will run a test on a Windows 10 computer and see if I can duplicate the problem.
